version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - pip install aws-sam-cli
  build:
    commands:
      - echo Entered the build and deploy phase...
      - echo Sam building...
      - sam build --parallel
      - echo Sam packaging...
      - |
        sam package \
          --s3-bucket nch-igm-cloudformation-artifacts-257995316808-us-east-1 \
          --s3-prefix dragen-aws-batch-quickstart \
          --output-template-file cf_template.yaml \
          --force-upload \
          --region us-east-1
      - echo Uploading dragen.zip to S3 artifacts bucket...
      - aws s3 cp app/packages/dragen/dragen.zip s3://nch-igm-cloudformation-artifacts-257995316808-us-east-1/dragen-aws-batch-quickstart/app/packages/dragen/dragen.zip
artifacts:
  files:
    - cf_template.yaml
    - samconfig.yaml
    - cicd/*
    - app/**/*
